name: ama-t3-upgrade-assistant
type: php
docroot: ~
no_project_mount: true
php_version: "8.1"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
    - v11.ama-t3-upgrade-assistant
additional_fqdns: []
provider: default
use_dns_when_possible: true
omit_containers:
    - dba
extra_services:
    - v11-data
