version: "3.6"
services:
    web:
        environment:
            - EXTENSION_KEY=ama_t3_upgrade_assistant
            - PACKAGE_NAME=nostadt/ama-t3-upgrade-assistant

            - TYPO3_INSTALL_DB_DRIVER=mysqli
            - TYPO3_INSTALL_DB_USER=root
            - TYPO3_INSTALL_DB_PASSWORD=root
            - TYPO3_INSTALL_DB_HOST=db
            - TYPO3_INSTALL_DB_PORT=3306
            - TYPO3_INSTALL_DB_UNIX_SOCKET=
            - TYPO3_INSTALL_DB_USE_EXISTING=0
            - TYPO3_INSTALL_ADMIN_USER=admin
            - TYPO3_INSTALL_ADMIN_PASSWORD=password
            - TYPO3_INSTALL_SITE_NAME=EXT:ama_t3_upgrade_assistant Dev Environment
            - TYPO3_INSTALL_SITE_SETUP_TYPE=site
            - TYPO3_INSTALL_WEB_SERVER_CONFIG=apache
        volumes:
            - type: bind
              source: ../
              target: /var/www/ama_t3_upgrade_assistant
              consistency: cached
            - v11-data:/var/www/html/v11
volumes:
    v11-data:
        name: "${DDEV_SITENAME}-v11-data"
